/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class falcon_classifier_PPM */

#ifndef _Included_edu_umass_cs_sensors_falcon_model_PPM
#define _Included_edu_umass_cs_sensors_falcon_model_PPM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     falcon_classifier_PPM
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_edu_umass_cs_sensors_falcon_model_PPM_init
  (JNIEnv *, jobject, jint, jint);
JNIEXPORT void JNICALL Java_edu_umass_cs_sensors_falcon_model_PPM_deinit
  (JNIEnv *, jobject);

/*
 * Class:     falcon_classifier_PPM
 * Method:    setTopK
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_umass_cs_sensors_falcon_model_PPM_setTopK
  (JNIEnv *, jobject, jint);

/*
 * Class:     falcon_classifier_PPM
 * Method:    getTopPredictions
 * Signature: (III)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_edu_umass_cs_sensors_falcon_model_PPM_getTopPredictions
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     falcon_classifier_PPM
 * Method:    getEventProbability
 * Signature: (IIII)D
 */
JNIEXPORT jdouble JNICALL Java_edu_umass_cs_sensors_falcon_model_PPM_getEventProbability
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     falcon_classifier_PPM
 * Method:    updateModel
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_edu_umass_cs_sensors_falcon_model_PPM_updateModel
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
